openapi: 3.0.3
info:
  title: Cache Management API
  description: 查詢快取管理 API
  version: 1.0.0

paths:
  /api/cache/stats:
    get:
      summary: 取得快取統計資訊
      operationId: getCacheStats
      tags:
        - Cache
      responses:
        '200':
          description: 快取統計
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheStats'

  /api/cache/clear:
    post:
      summary: 清除快取
      operationId: clearCache
      tags:
        - Cache
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pattern:
                  type: string
                  description: 要清除的快取鍵 pattern（支援 * 萬用字元）
                  example: "query:*"
                document_id:
                  type: string
                  description: 清除特定文件相關的快取
      responses:
        '200':
          description: 快取已清除
          content:
            application/json:
              schema:
                type: object
                properties:
                  deleted_count:
                    type: integer
                    description: 已刪除的快取數量
                  message:
                    type: string

  /api/cache/queries:
    get:
      summary: 列出快取的查詢
      operationId: listCachedQueries
      tags:
        - Cache
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
          description: 返回數量上限
        - name: sort_by
          in: query
          schema:
            type: string
            enum:
              - hit_count
              - created_at
            default: hit_count
          description: 排序方式
      responses:
        '200':
          description: 快取查詢列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  queries:
                    type: array
                    items:
                      $ref: '#/components/schemas/CachedQueryInfo'
                  total:
                    type: integer

  /api/cache/config:
    get:
      summary: 取得快取設定
      operationId: getCacheConfig
      tags:
        - Cache
      responses:
        '200':
          description: 快取設定
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheConfig'

    patch:
      summary: 更新快取設定
      operationId: updateCacheConfig
      tags:
        - Cache
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ttl:
                  type: integer
                  minimum: 60
                  maximum: 86400
                  description: 快取 TTL（秒）
                enabled:
                  type: boolean
                  description: 是否啟用快取
      responses:
        '200':
          description: 設定已更新
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheConfig'

components:
  schemas:
    CacheStats:
      type: object
      properties:
        total_keys:
          type: integer
          description: 總快取數量
        query_cache_count:
          type: integer
          description: 查詢快取數量
        task_cache_count:
          type: integer
          description: 任務快取數量
        memory_usage_bytes:
          type: integer
          description: 記憶體使用量（bytes）
        hit_rate:
          type: number
          format: float
          description: 快取命中率
        total_hits:
          type: integer
          description: 總命中次數
        total_misses:
          type: integer
          description: 總未命中次數

    CachedQueryInfo:
      type: object
      properties:
        cache_key:
          type: string
          description: 快取鍵
        query:
          type: string
          description: 原始查詢
        hit_count:
          type: integer
          description: 命中次數
        created_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
        ttl_remaining:
          type: integer
          description: 剩餘 TTL（秒）

    CacheConfig:
      type: object
      properties:
        enabled:
          type: boolean
          description: 是否啟用快取
        ttl:
          type: integer
          description: 預設 TTL（秒）
        max_memory:
          type: string
          description: 最大記憶體使用量
        redis_url:
          type: string
          description: Redis 連線 URL（已遮蔽）
